name: Deploy to Netlify

on:
  push:
    branches: [main] # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: arthhealthwebapp # Change to your React app directory
    
    - name: Build React app
      run: npm run build # Build the project, generating the build folder
      working-directory: arthhealthwebapp # Change to your React app directory

    - name: Trigger Netlify Build Hook
      run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }} # Trigger the Netlify build hook
