name: Deploy to Netlify

on:
  push:
    branches: [main] # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: arthhealthwebapp # Change to your React app directory
    
    - name: Build React app
      run: npm run build # Build the project, generating the build folder
      working-directory: arthhealthwebapp # Change to your React app directory

    - name: Install Netlify CLI
      run: npm install -g netlify-cli # Install Netlify CLI globally

    - name: Deploy to Netlify
      run: netlify deploy --dir=build --prod --auth=$NETLIFY_AUTH_TOKEN # Deploy the build folder to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} # Use the Netlify Auth Token from GitHub Secrets
