name: Deploy to Netlify

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up working directory
      run: ArthHealth/arthhealthwebapp # Change to your React app directory


    - name: Install dependencies
      run: npm install
    
    - name: Build React app
      run: npm run build # This assumes your React app is built using npm run build

    
    - name: "Deployed site"
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
